language: ruby
rvm:
- 2.6.3
before_install:
- cd date_spot-rails
- export GEM_HOME=$PWD/vendor/bundle/ruby/2.6.3
- gem install bundler
cache:
  directories:
  - date_spot-rails
services:
- postgresql
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: R5szqrafuD9lE+DlW0MLqQHnD/qz7ISDcFGu/uPbDjs6StHlCHEp1e8Rx5WAem2SSEeX1xj1OztUVw8+1RstgFv+Co2T1FrScjzDdhlvdL8gG3b4zf1Uf3KXWgGcwbarMiVA6xpfrSYnCHFZSCHgcge9ffpbIgs6l5TzUMQ6gyUeGkT6Un4eRixn+GVqDfA0qHz0XcQ5A3dnkbQbwOWE9NFX2qfE9t6923h1+U0osZ08B8wLD8sOJUEhVX+6i7QO0EjrhYys9wDxSsnp8IWwqziYz3i5F3d8ahvoZQJy6h/9NuVeUakqa0WovrIEdgTF0M7ZiOuZbw3yMqN7t0GYiSX+HPjrVYeX+gSpkzGEnFVEUKWsvxj1NFOb6uup8KV6yqhWpsmXQ+yc0K9r3eS8ICTVUVFrZfaC5FooazEEhcUtIMbMcXQrtaF1agxsGF2B9TkhGkrvvPdQSleBpoZgLE3rDZoO25Ijm1FivLPLRQY1XJiiL/a1LjGgoIjlGMgi7Hzvhp2LqillGLY1DX1I4KslkkZ5SlHazrzulACuM7koQlRE5hDvvK4Mn/eUxMuPUCeh9ie/5ULHDMQ4QHhi5NWGSqeoksXYi3xzM+bzGWhmmDi0uX4Z0CAr00V3Jrf9Tf5DbgQUH5Ir09uBB04zCSfkXBqXDbPav26FSVElRYQ=
  run:
  - rake pg:reset
  - rake db:migrate
  - rake db:seed
  app: date-spot-final
  on:
    repo: rafahg/travel-final-project
